#!/usr/bin/env python3
"""Regenerate src/defaults.c from the captured factory-default codeplugs in fixtures/.

These are not synthesised.  Each one was captured off the wire from the ORIGINAL software's
`INITIALIZE - 4 (reset to default)' path in the repair build, which is the only thing that knows
what a factory codeplug contains -- see doc/EEPROM_MAP_EZA.md and tools/eza.py default_codeplug().
Embedding them keeps `--new' honest: mcprog reproduces what the 1987 software produced, byte for
byte, rather than inventing a layout for the bytes nobody has mapped.

    python3 tools_gen_defaults.py > src/defaults.c
"""
import sys

# (model, band, file, what the band is).  Band 0 means the capture carries no band choice.
ENTRIES = [
    ('eza_sel5', 1, 'fixtures/eza9_default_band1.bin', 'RF range 1'),
    ('eza_sel5', 2, 'fixtures/eza9_default_band2.bin', 'RF range 2'),
    ('eza_sel5', 3, 'fixtures/eza9_default_band3.bin', 'RF range 3'),
    ('eza_sel5', 4, 'fixtures/eza9_default_band4.bin', 'RF range 4'),
    ('eza_cspl', 1, 'fixtures/ez13_default_band1.bin', 'RF range 1'),
    ('eza_cspl', 2, 'fixtures/ez13_default_band2.bin', 'RF range 2'),
    ('eza_cspl', 3, 'fixtures/ez13_default_band3.bin', 'RF range 3'),
    ('eza_cspl', 4, 'fixtures/ez13_default_band4.bin', 'RF range 4'),
    ('eva_sel5', 0, 'fixtures/ev9_default.bin',
     'no RF-range prompt exists in this build, so the band byte is left unset'),
]

out = sys.stdout
out.write('/* GENERATED by tools_gen_defaults.py -- do not edit by hand.\n'
          ' *\n'
          ' * Factory-default codeplugs, captured off the wire from the original software\'s\n'
          ' * INITIALIZE path (doc/EEPROM_MAP_EZA.md, tools/eza.py default_codeplug()).  Not\n'
          ' * synthesised: `--new\' reproduces what the 1987 repair build produced, byte for byte,\n'
          ' * which is why it can be trusted for the bytes this project has never mapped. */\n'
          '#include <string.h>\n'
          '#include "mc/codeplug.h"\n\n')
for model, band, path, what in ENTRIES:
    raw = open(path, 'rb').read()
    sym = 'DEF_%s_%d' % (model.upper(), band)
    out.write('/* %s -- %s, %d bytes */\n' % (path, what, len(raw)))
    out.write('static const uint8_t %s[%d] = {\n' % (sym, len(raw)))
    for i in range(0, len(raw), 12):
        out.write('\t' + ' '.join('0x%02X,' % b for b in raw[i:i+12]) + '\n')
    out.write('};\n\n')
out.write('static const mc_default DEFAULTS[] = {\n')
for model, band, path, what in ENTRIES:
    sym = 'DEF_%s_%d' % (model.upper(), band)
    out.write('\t{ "%s", %d, %s, sizeof %s, "%s" },\n' % (model, band, sym, sym, what))
out.write('};\n\n')
out.write('''const mc_default *mc_default_by_index(size_t i)
{
\treturn i < sizeof DEFAULTS / sizeof DEFAULTS[0] ? &DEFAULTS[i] : NULL;
}

const mc_default *mc_default_find(const char *model, int band)
{
\tconst mc_default *d;
\tsize_t i;

\tfor (i = 0; (d = mc_default_by_index(i)) != NULL; i++)
\t\tif (!strcmp(d->model, model) && (d->band == band || d->band == 0))
\t\t\treturn d;
\treturn NULL;
}
''')
